/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.pedroermarinho.hospital.Util;

//import com.qoppa.pdfWriter.PDFDocument;

import java.io.File;
import java.io.FileWriter;
import java.util.Date;
import java.util.Locale;

/**
 * @author Pedro Marinho < pedro.marinho238@gmail.com >
 */
public class PDF {

    public static void RELATORIO(String nome, int idade, String sexo, float peso, int altura, String nafs, int nam, int nfm, float quadril, String PAJ, String IMC, String IMC_S, String IAC, String IAC_S, String PI, String PI2, String PN, String TA, String TFB, String TMB, String AP) {
        System.out.println("RELATORIO");
        String site = "<html>\n"
                + "\n"
                + "<head>\n"
                + "<meta http-equiv=Content-Type content=\"text/html; charset=windows-1252\">\n"
                + "<meta name=Generator content=\"Microsoft Word 15 (filtered)\">\n"
                + "<style>\n"
                + "<!--\n"
                + " /* Font Definitions */\n"
                + " @font-face\n"
                + "	{font-family:\"Cambria Math\";\n"
                + "	panose-1:0 0 0 0 0 0 0 0 0 0;}\n"
                + "@font-face\n"
                + "	{font-family:Calibri;\n"
                + "	panose-1:2 15 5 2 2 2 4 3 2 4;}\n"
                + " /* Style Definitions */\n"
                + " p.MsoNormal, li.MsoNormal, div.MsoNormal\n"
                + "	{margin-top:0cm;\n"
                + "	margin-right:0cm;\n"
                + "	margin-bottom:8.0pt;\n"
                + "	margin-left:0cm;\n"
                + "	line-height:107%;\n"
                + "	font-size:11.0pt;\n"
                + "	font-family:\"Calibri\",sans-serif;}\n"
                + ".MsoPapDefault\n"
                + "	{margin-bottom:8.0pt;\n"
                + "	line-height:107%;}\n"
                + "@page WordSection1\n"
                + "	{size:595.3pt 841.9pt;\n"
                + "	margin:70.85pt 3.0cm 70.85pt 3.0cm;}\n"
                + "div.WordSection1\n"
                + "	{page:WordSection1;}\n"
                + "-->\n"
                + "</style>\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body lang=PT-BR>\n"
                + "\n"
                + "<div class=WordSection1>\n"
                + "\n"
                + "<p class=MsoNormal align=center style='text-align:center'><b><span\n"
                + "style='font-size:18.0pt;line-height:107%'>Ficha de Avaliação Física</span></b></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Nome: " + nome + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Idade: " + idade + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Peso: " + peso + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Altura (cm):\n"
                + "" + altura + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Quadril: " + quadril + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Sexo: " + sexo + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Número de Abdominais\n"
                + "por Minuto: " + nam + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Número de\n"
                + "Flexões por Minuto: " + nfm + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal><span style='font-size:12.0pt;line-height:107%'>Nível de\n"
                + "Atividade Física Semanais: " + nafs + "</span></p>\n"
                + "\n"
                + "<p class=MsoNormal align=center style='text-align:center'><span\n"
                + "style='font-size:16.0pt;line-height:107%'>Cálculos</span></p>\n"
                + "\n"
                + "<p class=MsoNormal>&nbsp;</p>\n"
                + "\n"
                + "<div align=center>\n"
                + "\n"
                + "<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0 width=0\n"
                + " style='width:436.85pt;border-collapse:collapse;border:none'>\n"
                + " <tr style='height:13.05pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>PAJ</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border:solid windowtext 1.0pt;\n"
                + "  border-left:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Peso Ajustado</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border:solid windowtext 1.0pt;\n"
                + "  border-left:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + PAJ + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:12.3pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>IMC</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Índice de Massa Corporal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + IMC_S + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:13.05pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>IAC</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Índice de Adiposidade Corporal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + IAC + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:12.3pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>PI</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Peso Ideal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + PI + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:13.05pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>PI2</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Peso Ideal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + PI2 + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:12.3pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>PN</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Peso Normal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + PN + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:13.05pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>TA</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Teste de Abdominal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + TA + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:13.05pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>TFB</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Teste de Flexão de Braço</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + TFB + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:12.3pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>TMB</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Taxa Metabólica Basal</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:12.3pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + TMB + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + " <tr style='height:13.05pt'>\n"
                + "  <td width=45 valign=top style='width:33.45pt;border:solid windowtext 1.0pt;\n"
                + "  border-top:none;padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>AP</span></p>\n"
                + "  </td>\n"
                + "  <td width=229 valign=top style='width:171.85pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>Adequação do Peso</span></p>\n"
                + "  </td>\n"
                + "  <td width=308 valign=top style='width:231.55pt;border-top:none;border-left:\n"
                + "  none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;\n"
                + "  padding:0cm 5.4pt 0cm 5.4pt;height:13.05pt'>\n"
                + "  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:\n"
                + "  normal'><span style='font-size:12.0pt'>" + AP + "</span></p>\n"
                + "  </td>\n"
                + " </tr>\n"
                + "</table>\n"
                + "\n"
                + "</div>\n"
                + "\n"
                + "<p class=MsoNormal>&nbsp;</p>\n"
                + "\n"
                + "<p class=MsoNormal>&nbsp;</p>\n"
                + "\n"
                + "<p class=MsoNormal>&nbsp;</p>\n"
                + "\n"
                + "<p class=MsoNormal>&nbsp;</p>\n"
                + "\n"
                + "</div>\n"
                + "\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        FileWriter arquivo;
        System.out.println("salvando");
        try {
            arquivo = new FileWriter(new File("Arquivo.html"));
            arquivo.write(site);
            arquivo.close();

            Locale ptBr = new Locale("pt", "BR");
            File f1 = new File("Arquivo.html");
            Date dt = new Date();
//            PDFDocument pdfDoc = PDFDocument.loadHTML(f1.toURI().toURL(), new PageFormat(), false);
//            pdfDoc.saveDocument("C:\\Users\\Public\\Documents\\" + nome + ".pdf");
            System.err.println("salvo");
        } catch (Exception ex) {
            System.err.println("não foi salvo");
            ex.printStackTrace();
        }

    }
}
